#!/usr/bin/env bash

What  is OSI model?
The OSI model is a conceptual model that characterizes the communication functions of a telecommunication system without regard to their underlying internal structure and technology

How is OSI mode organized?
From the lowest to the highest level
