#!/usr/bin/env bash
# Prints the time for 12 horus and 59 minutes.
#   Prints hours from 0 to 12
#   Prints minutes from 1 to 59

Hour=0

while [ "$Hour" -le 12 ]
do
  echo "Hour: $Hour"
  minute=1
  while [ "$minute" -le 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( Hour++ ))
done